services:
  frigate:
    container_name: frigate
    restart: unless-stopped
    stop_grace_period: 30s
    image: ${FRIGATE_IMAGE:-frigate:latest}
    shm_size: "4096mb"
    environment:
      GO2RTC_ALLOW_ARBITRARY_EXEC: "true"
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - ./debug:/media/frigate/debug:ro
      - /etc/localtime:/etc/localtime:ro
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "8971:8971"
      - "8554:8554"
      - "5000:5000"
      - "1984:1984"
      - "8555:8555/tcp"
      - "8555:8555/udp"
    depends_on:
      - mqtt

  mqtt:
    container_name: mqtt
    image: emqx/nanomq:latest-slim
    restart: unless-stopped
    environment:
      NANOMQ_CONF_PATH: /etc/nanomq.conf
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
    volumes:
      - ./nanomq/nanomq.conf:/etc/nanomq.conf:ro
      - ./nanomq/data:/var/lib/nanomq
