services:
  frigate:
    image: ${FRIGATE_IMAGE:-frigate:latest-rocm}
    group_add:
      - "${FRIGATE_RENDER_GID:-109}"
      - "${FRIGATE_VIDEO_GID:-44}"
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    environment:
      CONFIG_FILE: ${FRIGATE_CONFIG_FILE:-/config/config.amd.yml}
      LIBVA_DRIVER_NAME: radeonsi
